### PR TITLE
Address signingCert panic with the last-byte calculation of finalChainPEM

### LINKED ISSUE #369: panic at pkg/api/ca.go:signingCert(): runtime error: index out of range [830] with length 826
While setting up Fulcio on two separate machines, I've run into the following panic while invoking `cosign`:

```
2022-01-31T20:04:34.088-0800    INFO    api/ca.go:177   Submitting CTL inclusion for OIDC grant: t+github@chainguard.dev
2022-01-31T20:04:34.191-0800    INFO    api/ca.go:189   CTL Submission Signature Received: BAMARzBFAiBYkedZcZR8zeEJsEBK2AWxBwUaHSGWQrWJQdn1innyCAIhAI4dQTkHyPdthB1YeoHAKb9n09Hk2xPVT8DNgxpukI6m
2022-01-31T20:04:34.191-0800    INFO    api/ca.go:190   CTL Submission ID Received: x0C3nc20bfNYLYxRv4NiAuhGgHWJbCBbvMOr6BVlhT0=
2022/01/31 20:04:34 http: panic serving 127.0.0.1:48126: runtime error: index out of range [830] with length 826
goroutine 52 [running]:
net/http.(*conn).serve.func1(0x40001400a0)
        /usr/local/go/src/net/http/server.go:1802 +0xe4
panic({0xc66c80, 0x40001ce378})
        /usr/local/go/src/runtime/panic.go:1052 +0x2b4
github.com/sigstore/fulcio/pkg/api.(*api).signingCert(0x400065e300, {0x7f69aedfa0, 0x40001140a0}, 0x4000138200)
        /u/t/sigstore-local/src/fulcio/pkg/api/ca.go:216 +0x1178
net/http.HandlerFunc.ServeHTTP(0x400065c320, {0x7f69aedfa0, 0x40001140a0}, 0x4000138200)
        /usr/local/go/src/net/http/server.go:2047 +0x40
net/http.(*ServeMux).ServeHTTP(0x4000160680, {0x7f69aedfa0, 0x40001140a0}, 0x4000138200)
        /usr/local/go/src/net/http/server.go:2425 +0x18c
github.com/sigstore/fulcio/cmd/app.runServeCmd.func2.1({0x7f69aedfa0, 0x40001140a0}, 0x4000138100)
        /u/t/sigstore-local/src/fulcio/cmd/app/serve.go:194 +0x2c8
net/http.HandlerFunc.ServeHTTP(0x400065e320, {0x7f69aedfa0, 0x40001140a0}, 0x4000138100)
        /usr/local/go/src/net/http/server.go:2047 +0x40
github.com/prometheus/client_golang/prometheus/promhttp.InstrumentHandlerDuration.func1({0xde6b78, 0x40005300e0}, 0x4000138100)
        /u/t/go/pkg/mod/github.com/prometheus/client_golang@v1.12.1/prometheus/promhttp/instrument_server.go:76 +0xe0
net/http.HandlerFunc.ServeHTTP(0x4000160700, {0xde6b78, 0x40005300e0}, 0x4000138100)
        /usr/local/go/src/net/http/server.go:2047 +0x40
github.com/sigstore/fulcio/pkg/api.WithMaxBytes.func1({0xde6b78, 0x40005300e0}, 0x4000138100)
        /u/t/sigstore-local/src/fulcio/pkg/api/max_bytes.go:25 +0x138
net/http.HandlerFunc.ServeHTTP(0x400065e360, {0xde6b78, 0x40005300e0}, 0x4000138100)
        /usr/local/go/src/net/http/server.go:2047 +0x40
net/http.serverHandler.ServeHTTP({0x40005301c0}, {0xde6b78, 0x40005300e0}, 0x4000138100)
        /usr/local/go/src/net/http/server.go:2879 +0x45c
net/http.(*conn).serve(0x40001400a0, {0xdebf98, 0x400015a9f0})
        /usr/local/go/src/net/http/server.go:1930 +0xb54
created by net/http.(*Server).Serve
        /usr/local/go/src/net/http/server.go:3034 +0x4ac
```

I believe this behavior was introduced by https://github.com/sigstore/fulcio/commit/10262db828ecf78e4bb087a7a35be64b4fbaf9d2 -- here is the line in particular that I believe is causing the panic:

https://github.com/sigstore/fulcio/blob/4bd818d4bf909169e4ac24ebbaa805fe60f153b8/pkg/api/ca.go#L216

It seems to be using finalChainPEM to calculate a change to finalPEM. However, in my case, finalPEM is shorter (826 bytes) than finalChainPEM (831 bytes), so it causes a panic.

### LINKED ISSUE #639: What does the email in a Fulcio certificate mean?
It's becoming clear that we're not telling a consistent story about "Fulcio identities." I filed https://github.com/sigstore/cosign/issues/1947 to address the fact that I've seen a number of instances where users recommended passing the `--cert-email` flag to Cosign without checking the issuer. Because there's overlap in the email subjects that different Fulcio IdPs issue tokens for (that is, Google and Microsoft will both give you a token for user@example.com), this gives you least-common-denominator security for a policy that only checks emails: if I made my Microsoft account 10 years ago to play Xbox and with password "ZackPwnsN00bs" and no 2FA, someone can compromise that account and publish artifacts that are trusted in the same manner as if they compromised my Google account *with* 2FA. That's clearly a bad idea, and I believe that it's due to a lack of clarity as to what a Fulcio certificate *means*.

For instance, everything seems more consistent if we *don't* use emails everywhere, and instead use usernames. Then, it's really obvious that "znewman01 via Microsoft" isn't necessarily the same entity as "znewman01 via GitHub." I'm not necessarily advocating for this change, but that seems to be closer to what's happening conceptually right now.

However, the documentation for the project doesn't reflect that: the README currently says that Fulcio "issu[es] certificates based on an OIDC email address." `security-model.md` says "Fulcio assumes that a valid OIDC token is a sufficient 'proof of ownership' of an email address." I believe that the stress on email suggests something very different than what it is actually happening. I could have made a Microsoft account with an email 10 years ago, then lost that email, but still remember my password—I'm just demonstrating control of the Microsoft account, *not* the email. Similarly, this relies on *every* OIDC provider to maintain a certain standard of email verification. 

I believe that we should have guidance on the following:

- what does a Fulcio certificate actually attest to?
- how should I, the end user, think of the various identities in play?

Then, once we have that clarified, we should:

- think about how to best explain this to end users
- think about how to best expose this abstraction in libraries and APIs 

Related reading:

- https://github.com/sigstore/cosign/issues/1947 lots of arguing/philosophizing
- https://github.com/sigstore/fulcio/issues/371 discussion about why "email verification flow" isn't up to Fulcio standards
- https://github.com/sigstore/fulcio/issues/444 request for a new IdP
- https://github.com/sigstore/fulcio/issues/397 in-progress list of requirements for adding a new IdP to Fulcio

### PR DESCRIPTION
**Pull request by tstromberg**
Signed-off-by: Thomas Stromberg <t+github@stromberg.org>

#### Summary

Addresses a panic caused by the incorrect string being referred for a newline check.

This panic only occurs if finalPEM is shorter than finalChainPEM.

#### Ticket Link

Fixes #369

#### Release Note

```release-note
NONE
```

### CODE REVIEW

File: pkg/api/ca.go [hunk 1]
```diff
@@ -213,7 +213,7 @@ func (a *api) signingCert(w http.ResponseWriter, req *http.Request) {
 	}
 	if len(finalChainPEM) > 0 {
 		fmt.Fprintf(&ret, "%s", finalChainPEM)
-		if finalPEM[len(finalChainPEM)-1] != '\n' {
+		if finalChainPEM[len(finalChainPEM)-1] != '\n' {
```
Comment (nsmith5) [inline pkg/api/ca.go:216]: Nit: Perhaps this might be more clear if we'd written as 

```suggestion
		if !strings.HasSuffix(string(finalChainPEM), "\n") {
```

Comment (tstromberg) [reply pkg/api/ca.go]: Great idea. Done!

**Review by nsmith5 — APPROVED** [review]

**Review by haydentherapper — APPROVED** [review]
Great catch! I had added this check. This suggests to me we need some additional tests.

**Comment by haydentherapper** [comment]
@bobcallaway @dlorenc - Not sure when the last Fulcio release was, but if it's been pushed after https://github.com/sigstore/fulcio/commit/10262db828ecf78e4bb087a7a35be64b4fbaf9d2, we'll want to get this change in and pushed.

**Review by dlorenc — APPROVED** [review]

**Comment by dlorenc** [comment]
> @bobcallaway @dlorenc - Not sure when the last Fulcio release was, but if it's been pushed after [10262db](https://github.com/sigstore/fulcio/commit/10262db828ecf78e4bb087a7a35be64b4fbaf9d2), we'll want to get this change in and pushed.

Ack, deploying after this one!
